# Generated by Django 3.2.9 on 2021-11-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=16)),
                ('passwords', models.CharField(max_length=20)),
                ('mails', models.CharField(max_length=20)),
            ],
        ),
    ]
